server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    application-id: zillow-kafka-elastic9
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rent-stream-processor9

app:
  out:
    topic: zillow_rent_enriched_data_out
  input:
    topic: zillow_rent_data_input_01

schema:
  registry:
    url: http://localhost:8081